# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: group, action: index }

# group edition (registered user only)
group_admin:
  class: sfPropel15RouteCollection
  options:
    model:                Group
    module:               group_admin
    prefix_path:          /group
    actions:              [new, create, edit, update, delete]
    column:               name
    with_wildcard_routes: true
    with_show:            false

# group read-only (guest + registered users)
group:
  class: sfPropel15RouteCollection
  options:
    model:                Group
    module:               group
    prefix_path:          /group
    actions:              [show]
    column:               name
    with_wildcard_routes: true
    with_show:            true

# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
