# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: group, action: index }

# Accept invitation
invitation_accept:
  url: /invitation/reply/:invitation/accept
  param: { module: invitation, action: accept }

# Decline invitation
invitation_decline:
  url: /invitation/reply/:invitation/accept
  param: { module: invitation, action: decline }

# Re-send invitation to a group
invitation_group:
  url: /invitation/group/:group_name
  param: { module: invitation, action: resendGroup }

# Re-send invitation to one user
invitation_user:
  url: /invitation/user/:user/:group_name
  param: { module: invitation, action: resendUser }

# group edition (registered user only)
group_admin:
  class: sfPropel15RouteCollection
  options:
    model:                Group
    module:               group_admin
    prefix_path:          /g
    actions:              [new, create, edit, update, delete]
    column:               name
    with_wildcard_routes: true
    with_show:            false

# group read-only (guest + registered users)
group:
  class: sfPropel15RouteCollection
  options:
    model:                Group
    module:               group
    prefix_path:          /g
    actions:              [show]
    column:               name
    with_wildcard_routes: true
    with_show:            true

# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
