generator:
  class: sfPropelGenerator
  param:
    model_class:           Group
    theme:                 admin15
    non_verbose_templates: true
    with_show:             false
    singular:              Group
    plural:                Groups
    route_prefix:          group
    with_propel_route:     1
    actions_base_class:    gzActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
