<?php



/**
 * Skeleton subclass for representing a row from the 'gz_group_member' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.4 on:
 *
 * Thu Sep 23 21:16:36 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class GroupMember extends BaseGroupMember {

  public function __toString()
  {
    return $this->getGroupId().'-'.$this->getUserId();
  }

	/**
	 * Code to be run after inserting to database to notify the dispatcher
	 * @param PropelPDO $con
	 */
	public function postInsert(PropelPDO $con = null)
  {
    // Add the user to the mailing list
    $event = new sfEvent ($this, 'gz_member.join');
    sfContext::getInstance()->getEventDispatcher()->notify($event);

    return parent::postInsert ($con);
  }

	/**
	 * Code to be run before deleting from database to notify the dispatcher
	 * @param PropelPDO $con
	 */
	public function preDelete(PropelPDO $con = null)
  {
    // Add the user to the mailing list
    $event = new sfEvent ($this, 'gz_member.leave');
    sfContext::getInstance()->getEventDispatcher()->notify($event);

    return parent::preDelete ($con);
  }

} // GroupMember
