<?php



/**
 * Skeleton subclass for representing a row from the 'gz_group_member' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.4 on:
 *
 * Thu Sep 23 21:16:36 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class GroupMember extends BaseGroupMember {

  public function __toString()
  {
    return $this->getGroupId().'-'.$this->getUserId();
  }

  /**
   * Code to be run after inserting to database to notify the dispatcher
   * @param PropelPDO $con
   */
  public function postInsert(PropelPDO $con = null)
  {
    // Add the user to the mailing list
    sfProjectConfiguration::getActive()->getEventDispatcher()->notify(
      new sfEvent ($this, 'gz.member.joined'));

    return parent::postInsert ($con);
  }

  /**
   * Code to be run after deleting from database to notify the dispatcher
   * @param PropelPDO $con
   */
  public function postDelete(PropelPDO $con = null)
  {
    // Add the user to the mailing list
    sfProjectConfiguration::getActive()->getEventDispatcher()->notify(
      new sfEvent ($this, 'gz.member.leaved'));

    return parent::postDelete ($con);
  }

} // GroupMember
