<?php



/**
 * Skeleton subclass for performing query and update operations on the 'gz_invitation' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.4 on:
 *
 * Thu Sep 23 21:16:36 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class InvitationPeer extends BaseInvitationPeer {

  public static function createInvitation (Group $group, User $user)
  {
    // Check if an invitation isn't still pending
    $invitation = InvitationQuery::create ()
      ->filterByGroup ($group)
      ->filterByUser ($user)
      ->findOne ();

    if ($invitation !== null)
      return $invitation;

    $invitation = new Invitation ();
    $invitation->setGroup ($group);
    $invitation->setUser ($user);
    $invitation->setHash (sha1 ($user->getId().$group->getId().time().mt_rand()));
    $invitation->save ();

    // TODO try catch in case of sha1 collision : catch () { Play LOTO }

    return $invitation;
  }

} // InvitationPeer
