<?php



/**
 * Skeleton subclass for representing a row from the 'gz_user' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.4 on:
 *
 * Thu Sep 23 21:16:36 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class User extends BaseUser {

  public function __toString()
  {
    return $this->getFullname();
  }

  public function getFullname()
  {
    return $this->getFirstname().' '.$this->getLastname();
  }

  /**
   * Set the value of [mail] column.
   *
   * @param      string $v new value
   * @return     User The current object (for fluent API support)
   */
  public function setMail($v)
  {
    parent::setMail(strtolower($v));
  }


  /**
   * Alias of User::getIsGuest()
   * 
   * @return boolean
   */
  public function isGuest ()
  {
    return $this->getIsGuest();
  }

  /**
   * Return the list of groups the user is member of but not the creator.
   *
   * @return PropelObjectCollection
   */
  public function getFollowedGroups ()
  {
    return $this->getGroups(); // TODO need to be changed if we include the user in the group members (implicit now)
  }

} // User
