propel:

  gz_group:
    _attributes :   { phpName: Group }
    _propel_behaviors:
      blameable:
    id: ~
    name:           { type: varchar(255), required: true, index: unique }
    title:          { type: varchar(255), required: true }
    is_public:      { type: boolean,      required: true, default: true }
    description:    { type: longvarchar,  required: true }
    expires_notice: { type: boolean,      default: false } # true if sent, false else
    expires_at:     { type: timestamp,    required: true }
    deleted:        { type: integer,      required: true, default: 0 }
    created_by:     { type: integer,      required: true }
    created_at: ~
    updated_at: ~

    _foreignKeys:
      owner:
        foreignTable: gz_user
        phpName: Owner
        refPhpName: CreatedGroup
        references:
          - { local: created_by, foreign: id }

  gz_user:
    _attributes :   { phpName: User }
    id: ~
    is_guest:       { type: boolean, required: true, default: false } # does the user comes from the ldap or not
    added_by:       { type: integer       } # if the user is not internal, store the person who invited him
    firstname:      { type: varchar(255) }
    lastname:       { type: varchar(255) }
    email:          { type: varchar(255) }
    org:            { type: varchar(255) }
    tel:            { type: varchar(10)  }
    password:       { type: varchar(40)  } # SHA1
    created_at: ~

  gz_group_member:
    _attributes :   { phpName: GroupMember, isCrossRef: true }
    group_id:       { type: integer, primaryKey: true, required: true, foreignTable: gz_group, foreignReference: id }
    user_id:        { type: integer, primaryKey: true, required: true, foreignTable: gz_user,  foreignReference: id }

  gz_invitation:
    _attributes :   { phpName: Invitation }
    group_id:       { type: integer, primaryKey: true, required: true, foreignTable: gz_group, foreignReference: id }
    user_id:        { type: integer, primaryKey: true, required: true, foreignTable: gz_user,  foreignReference: id }
    hash:           { type: varchar(40), index: unique } # SHA1 invitation code
    created_at: ~

